In [1]:
from chess import AI
import numpy as np

ai = AI(8, 1, 5000)
chessboard = np.zeros((8, 8), dtype=int)
print(chessboard.shape)
chessboard[3][3] = chessboard[4][4] = 1
chessboard[3][4] = chessboard[4][3] = -1
print(chessboard)
ai.go(chessboard)
for item in ai.candidate_list:
    chessboard[item[0]][item[1]] = 5
print(chessboard)


(8, 8)
[[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  1 -1  0  0  0]
 [ 0  0  0 -1  1  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]]
[[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  5  5  5  0  0  0]
 [ 0  0  5  1 -1  5  0  0]
 [ 0  0  5 -1  1  5  0  0]
 [ 0  0  0  5  5  5  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]]


In [5]:
pos_board = []
row = []
row_bin = []
for power in range(64):
    row.append(1<<power)
    row_bin.append(bin(1<<power))
    if power % 8 == 7:
        #print(row)
        #print(row_bin)
        pos_board.append(row.copy())
        row.clear()
        row_bin.clear()
print(pos_board)

print()
for row in range(len(pos_board)):
    for col in range(len(pos_board[0])):
        print(str(pos_board[row][col]) + ": (" + str(row) + ", " + str(col) + ")")

[[1, 2, 4, 8, 16, 32, 64, 128], [256, 512, 1024, 2048, 4096, 8192, 16384, 32768], [65536, 131072, 262144, 524288, 1048576, 2097152, 4194304, 8388608], [16777216, 33554432, 67108864, 134217728, 268435456, 536870912, 1073741824, 2147483648], [4294967296, 8589934592, 17179869184, 34359738368, 68719476736, 137438953472, 274877906944, 549755813888], [1099511627776, 2199023255552, 4398046511104, 8796093022208, 17592186044416, 35184372088832, 70368744177664, 140737488355328], [281474976710656, 562949953421312, 1125899906842624, 2251799813685248, 4503599627370496, 9007199254740992, 18014398509481984, 36028797018963968], [72057594037927936, 144115188075855872, 288230376151711744, 576460752303423488, 1152921504606846976, 2305843009213693952, 4611686018427387904, 9223372036854775808]]



TypeError: 'int' object is not iterable

In [4]:
pos_values = []
test_ = 0

for row in range(7):
    for col in range(7):
        temp = pos_board[row][col]
        temp |= pos_board[col][row]
        temp |= pos_board[7 - row][col]
        temp |= pos_board[col][7 - row]
        temp |= pos_board[row][7 - col]
        temp |= pos_board[7 - col][row]
        temp |= pos_board[7 - row][7 - col]
        temp |= pos_board[7 - col][7 - row]
        if temp not in pos_values:
            pos_values.append(temp)
            print(bin(temp)[::-1])
            test_ ^= temp
print("test", bin(test_))
print(pos_values)

1000000100000000000000000000000000000000000000000000000010000001b0
010000101000000100000000000000000000000000000000100000010100001b0
00100100000000001000000100000000000000001000000100000000001001b0
0001100000000000000000001000000110000001000000000000000000011b0
0000000001000010000000000000000000000000000000000100001b0
000000000010010001000010000000000000000001000010001001b0
00000000000110000000000001000010010000100000000000011b0
0000000000000000001001000000000000000000001001b0
000000000000000000011000001001000010010000011b0
0000000000000000000000000001100000011b0
test 0b1111111111111111111111111111111111111111111111111111111111111111
[9295429630892703873, 4792111478498951490, 2594215222373842980, 1729382813125312536, 18577348462920192, 10205666933351424, 6755684016199680, 39582420959232, 26543503441920, 103481868288]


In [2]:
print(1<<128)
print(type(1<<128))

340282366920938463463374607431768211456
<class 'int'>
