In [3]:
from chess import AI
import numpy as np

ai_black = AI(8, -1, 5000)
ai_white = AI(8, 1, 5000)
chessboard = np.zeros((8, 8), dtype=int)

indices = [(3, 3), (4, 4)]
for index in indices:
    chessboard[index]= 1
    
indices = [(3, 4), (4, 3)]
for index in indices:
    chessboard[index]= -1
print(chessboard)

ai_white.go(chessboard)
for move in ai_white.candidate_list:
    chessboard[move[0]][move[1]] = 2
print(chessboard)

# ai_white.go(chessboard)
# move = ai_white.candidate_list.pop()
# chessboard[move[0]][move[1]] = 1
# print(chessboard)

# ai_black.go(chessboard)
# move = ai_black.candidate_list.pop()
# chessboard[move[0]][move[1]] = -1
# print(chessboard)


[[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  1 -1  0  0  0]
 [ 0  0  0 -1  1  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]]
[[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  1 -1  0  0  0]
 [ 0  0  0 -1  1  0  0  0]
 [ 0  0  0  1  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]]
[[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  1 -1  0  0  0]
 [ 0  0  0 -1  1  0  0  0]
 [ 0  0  0  1 -1  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]]


In [7]:
pos_board = []
row = []
row_bin = []
for power in range(64):
    row.append(1<<power)
    row_bin.append(bin(1<<power))
    if power % 8 == 7:
        #print(row)
        #print(row_bin)
        pos_board.append(row.copy())
        row.clear()
        row_bin.clear()
print(pos_board)

print()
for row in range(len(pos_board)):
    for col in range(len(pos_board[0])):
        print(str(pos_board[row][col]) + ": (" + str(row) + ", " + str(col) + ")", end=", ")

[[1, 2, 4, 8, 16, 32, 64, 128], [256, 512, 1024, 2048, 4096, 8192, 16384, 32768], [65536, 131072, 262144, 524288, 1048576, 2097152, 4194304, 8388608], [16777216, 33554432, 67108864, 134217728, 268435456, 536870912, 1073741824, 2147483648], [4294967296, 8589934592, 17179869184, 34359738368, 68719476736, 137438953472, 274877906944, 549755813888], [1099511627776, 2199023255552, 4398046511104, 8796093022208, 17592186044416, 35184372088832, 70368744177664, 140737488355328], [281474976710656, 562949953421312, 1125899906842624, 2251799813685248, 4503599627370496, 9007199254740992, 18014398509481984, 36028797018963968], [72057594037927936, 144115188075855872, 288230376151711744, 576460752303423488, 1152921504606846976, 2305843009213693952, 4611686018427387904, 9223372036854775808]]

1: (0, 0), 2: (0, 1), 4: (0, 2), 8: (0, 3), 16: (0, 4), 32: (0, 5), 64: (0, 6), 128: (0, 7), 256: (1, 0), 512: (1, 1), 1024: (1, 2), 2048: (1, 3), 4096: (1, 4), 8192: (1, 5), 16384: (1, 6), 32768: (1, 7), 65536: (2

In [4]:
pos_values = []
test_ = 0

for row in range(7):
    for col in range(7):
        temp = pos_board[row][col]
        temp |= pos_board[col][row]
        temp |= pos_board[7 - row][col]
        temp |= pos_board[col][7 - row]
        temp |= pos_board[row][7 - col]
        temp |= pos_board[7 - col][row]
        temp |= pos_board[7 - row][7 - col]
        temp |= pos_board[7 - col][7 - row]
        if temp not in pos_values:
            pos_values.append(temp)
            print(bin(temp)[::-1])
            test_ ^= temp
print("test", bin(test_))
print(pos_values)

1000000100000000000000000000000000000000000000000000000010000001b0
010000101000000100000000000000000000000000000000100000010100001b0
00100100000000001000000100000000000000001000000100000000001001b0
0001100000000000000000001000000110000001000000000000000000011b0
0000000001000010000000000000000000000000000000000100001b0
000000000010010001000010000000000000000001000010001001b0
00000000000110000000000001000010010000100000000000011b0
0000000000000000001001000000000000000000001001b0
000000000000000000011000001001000010010000011b0
0000000000000000000000000001100000011b0
test 0b1111111111111111111111111111111111111111111111111111111111111111
[9295429630892703873, 4792111478498951490, 2594215222373842980, 1729382813125312536, 18577348462920192, 10205666933351424, 6755684016199680, 39582420959232, 26543503441920, 103481868288]


In [7]:
num = 514
print(bin(num))
count = 0
while(num > 0):
    count += 1
    num &= num - 1
print(count)

0b1000000010
2
